name: Scraper - 3dmx

on:
  workflow_dispatch:  # Toto ponecháme, aby si ho mohol spustiť ručne

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout kód
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pandas requests beautifulsoup4 lxml

    - name: Run Script
      run: python -u 3dmx.py

    - name: Save CSV to repo
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        # 1. Najprv súbory pridáme a urobíme commit (uložíme ich lokálne u robota)
        git add *.csv
        git commit -m "Auto-update feeds $(date)" || echo "No changes to commit"
        # 2. Potom stiahneme prípadné zmeny z GitHubu a dáme naše zmeny "navrch"
        git pull --rebase
        # 3. A až teraz to všetko naraz pošleme hore
        git push
