name: Scraper - 3dmx

on:
  workflow_dispatch:  # Toto ponecháme, aby si ho mohol spustiť ručne

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout kód
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pandas requests beautifulsoup4 lxml

    - name: Run Script
      run: python -u 3dmx.py

    - name: Save CSV to repo
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        # 1. NAJPRV súbory pridáme a urobíme commit (tým ich "uzamkneme" u robota)
        git add *.csv
        git commit -m "Auto-update feeds $(date)" || echo "Žiadne zmeny"
        
        # 2. POTOM stiahneme zmeny z GitHubu (rebase ich hladko spojí)
        git pull --rebase
        
        # 3. NAKONIEC to pošleme hore
        git push
