name: Scraper - 3dmx

on:
  workflow_dispatch:  # Toto ponecháme, aby si ho mohol spustiť ručne

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout kód
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pandas requests beautifulsoup4 lxml

    - name: Run Script
      run: python -u 3dmx.py

  - name: Save CSV to repo
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        # 1. Pridáme súbory
        git add *.csv
        
        # 2. Urobíme commit (TOTO JE NAJDÔLEŽITEJŠIE - uzavrie zmeny u robota)
        git commit -m "Auto-update feeds $(date)" || echo "No changes"
        
        # 3. Teraz stiahneme zmeny z webu a naše pridáme navrch
        git pull --rebase origin main
        
        # 4. A pošleme to domov
        git push origin main
