name: Scraper - Alexim Full

on:
  schedule:
    # Spúšťa sa každé 4 hodiny
    - cron: '0 */4 * * *'
  workflow_dispatch: # Tlačidlo na manuálne spustenie

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout kód
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests beautifulsoup4 lxml

      - name: Run Alexim Script
        run: python -u Alexim.py

      - name: Save CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add alexim_sklad.csv
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Full update: $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
