- name: Save and Push Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add basys_sklad.csv
          
          if git diff --staged --quiet; then
            echo "Žiadne zmeny."
          else
            git commit -m "Basys update: $(date +'%Y-%m-%d %H:%M')"
            
            # TOTO JE OPRAVA: Stiahne zmeny od ostatných skriptov a tvoje pridá k nim
            git pull --rebase origin main
            
            git push origin main
          fi
