name: MusicPark Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    # TOTO PRIDAJ: uvidíš logy okamžite, nebude to "stáť"
    env:
      PYTHONUNBUFFERED: 1
    permissions:
      contents: write
    steps:
      - name: Checkout kódu
        uses: actions/checkout@v3

      - name: Nastavenie Pythonu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Inštalácia závislostí
        run: |
          pip install requests beautifulsoup4 pandas lxml

      - name: Spustenie scrapera
        run: python musicpark.py

      - name: Commit a Push výsledkov
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Pridáme -f (force) alebo kontrolu existencie, aby to nepadlo
          git add musicpark_sklad.csv
          git commit -m "Aktualizácia dát: $(date)" || echo "Žiadne zmeny na commit"
          git push
