name: All Suppliers Scraper

on:
  schedule:
    - cron: '0 4,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout k√≥d
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pandas requests beautifulsoup4 lxml

    - name: Run Scripts
      run: |
        python -u imusic.py
        python -u musicpark.py
        python -u musictrade.py
        python -u rockster.py
        python -u 3dmx.py
        python -u imusicdata.py
        python -u alexim.py
        python -u basys.py
        python -u eprodance.py

    - name: Save CSVs to repo
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add *.csv
        git pull --rebase
        git commit -m "Auto-update all 9 feeds $(date)" || echo "No changes"
        git push
